baseurl = "https://largekind.gitlab.io/Til/"
title = "largekind TIL"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
theme = "npqhugo"
pygmentsUseClasses=true

languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true

enableGitInfo = true
[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
[params]
  author = "largekind"
  description = "An engineer of sorts."
  keywords = "Today I learned"
  useAvatar = true
  microBlogSection = "posts"
  displayMicroBlog = true
  displayRecent = true
  recentMax = 4
  mail = "3191524-largekind@users.noreply.gitlab.com"
[menu]
  [[menu.main]]
    name = "home"
    pre = "<i class=\"fas fa-home fa-sm\"></i>"
    url = "/"
    weight = -9
  [[menu.main]]
    name = "about"
    pre = "<i class=\"fas fa-seedling\"></i>"
    url = "/about"
    weight = -9
  [[menu.main]]
    name = "blog"
    pre = "<i class=\"fas fa-keyboard fa-ms\"></i>"
    url = "/blog/"
    weight = -8
  [[menu.main]]
    name = "categories"
    pre = "<i class=\"fas fa-list fa-ms\"></i>"
    url = "/categories/"
    weight = -7
  [[menu.main]]
    name = "tags"
    pre = "<i class=\"fas fa-tags fa-ms\"></i>"
    url = "/tags"
    weight = -6
  [[menu.main]]
    name = "gitlab"
    pre = "<i class=\"fab fa-gitlab fa-ms\"></i>"
    url = "https://gitlab.com/largekind"
    weight = -5
  [[menu.main]]
    name = "github"
    pre = "<i class=\"fab fa-github fa-ms\"></i>"
    url = "https://github.com/largekind"
    weight = -4
  [[menu.main]]
    name = "RSS"
    pre = "<i class=\"fas fa-rss fa-ms\"></i>"
    url = "/index.xml"
    weight = -3
  [[menu.main]]
    name = "contact"
    pre = "<i class=\"far fa-envelope\"></i>"
    url = "/contact"
    weight = -1
[module]
[[module.mounts]]
  excludeFiles = 'blog/Python/avilen/*'
  source = 'content'
  target = 'content'